version: '2'
services:
    prodjhipstest-app:
        image: prodjhipstest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://prodjhipstest-postgresql:5432/ProdJhipsTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    prodjhipstest-postgresql:
        extends:
            file: postgresql.yml
            service: prodjhipstest-postgresql
